### ISSUE TITLE
DOMException: Failed to execute 'setItem' on Storage

### ISSUE THREAD

**Issue by sinosoidal** [Selz/jquery.selz#11]
Hey guys,

I have already reported this situation through Selz support but maybe this way I will have your direct attention.

I'm facing an issue in which the Selz plugin doesn't trigger the overlay. Today I have found the following on the Javascript console:

![screen shot 2017-12-13 at 17 23 32](https://user-images.githubusercontent.com/1700060/33953644-92f3986c-e02d-11e7-8515-83f8eefaf050.png)

After clearing the cache, the error disappeared and the overlay didn't failed anymore... so far!

Is this a bug? Can't you store this data elsewhere? Because this was basically happening all the time on my browser. We can't control the users browser data and this must work all the times.

In my case, we are relying on the Selz plugin to show an overlay on the website product page (https://www.imaginando.pt/products/drc) and when it is not shown, a new tab is open and we loose the javascript callbacks that will trigger the after purchase actions...

PS: I loved the comment on line 34! Hilarious! 🤣

**Comment by sampotts** [comment]
Ahh, I think the issue here is that we check we can use local storage but only with a tiny bit of data (`OK`) to test with and if the storage is at 99% of quota then that won't help. I'll wrap the actual `.setData(...)` in a try/catch too, given the caching is not really critical for operation. This would be super edge case I think though unless the site the plugin on is *heavily* using local/session storage as you get at least 5MB from memory (most are 10MB). Anyhow, I'll get this fixed up.

Heh, I probably should edit that line 👍

**Comment by sinosoidal** [comment]
Thanks for looking at this. Let me know when you have news! Best regards

**Comment by sampotts** [comment]
This should be resolved in the latest version - let me know 👍

**Comment by sinosoidal** [comment]
Thanks! Will try! Best

**Comment by sinosoidal** [comment]
@sampotts forgot to tell you that the issue was resolved! Thanks for your efforts. Best!

**Comment by sampotts** [comment]
@sinosoidal Awesome! Apologies about the mixup with support. They had lodged a ticket in Trello for us to take a look but I saw (and fixed) the issue on here before I got to the ticket in Trello. A bit of an internal mixup. Sorry about that.
