### ISSUE TITLE
Modal dialog doesn't open on mobile devices

### ISSUE THREAD

**Issue by gallien** [Selz/jquery.selz#7]
We have integrated the Selz plugin with option 'checkout: true' on following URL :
https://goo.gl/mAeT25
(Button 'JETZT KAUFEN')

The modal dialog opens on desktop, but a new page opens on iPhone and iPad. The back and close button on the new opened page also doesn't work correctly. Is your plugin mobile ready?

**Comment by SamPotts** [comment]
Hey @gallien , this is intended behavior. We made the decision to open a tab on mobile devices due to the issues with overlay modal windows on iOS and some versions of Android. It's not ideal we know but it at least allows the checkout to function correctly on these devices. We will investigate why the close and back buttons are not working and see if the latest versions of iOS and Android have improved their support for `position: fixed` modal windows.

**Comment by SamPotts** [comment]
Hey @gallien , sorry about the delay. I did some more digging and found a solution for iOS and Android devices. This was an issue that also effected Bootstrap if you're familiar with it, and they found a work around that we've put in place. You don't need to update any code your end, it should just work on iOS and Android now.
